source 'https://github.com/CocoaPods/Specs.git'
pod 'FSPagerView'
pod 'ElongationPreview'
platform :ios, '10.1'
use_frameworks!
target 'StudioApp' do
pod 'SnapKit', '~> 4.0.0'
pod 'BMPlayer', '~> 1.0.0'
pod 'SVProgressHUD'
pod 'SwiftyJSON'
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
end


