source 'https://github.com/CocoaPods/Specs.git'
pod ‘ASExtendedCircularMenu’, :git => 'https://github.com/anshul18895/ASExtendedCircularMenu'
pod 'FSPagerView'
platform :ios, '10.1'
use_frameworks!
target 'StudioApp' do
pod 'SnapKit', '~> 4.0.0'
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
end


